apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: web
spec:
  containers:
    - name: hello-world
      image: reddeppas/node-web-app
      ports:
        - containerPort: 80
